theme = "hyde"
# theme = 'ananke'
title = "A lazy blog"
languageCode = 'en-us'
[params]
    description = "Some stuff over the years, some stuff is new"

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
